name: Convert local cache to github cache
on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write # require to delete cache

jobs:

  conv-cache:
    name: Convert cache
    runs-on: ubuntu-latest
    env:
      cache-key: anilist_cache
    steps:
    - name: Checkout current code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install alfetcher
    - name: Determine Python version
      id: python_version
      run: |
        full_version=$(python --version | cut -d' ' -f2)
        major_version=$(echo $full_version | grep -oE '^[^.]+.[^.]+')
        echo "::set-output name=full_version::$full_version"
        echo "::set-output name=major_version::$major_version"
    - name: Download cache and extract it to appropriate dir
      shell: bash
      run: |
        curl -o cache.zip ${{ vars.CACHE_URL }}
        unzip cache.zip -d /opt/hostedtoolcache/Python/${{ steps.python_version.outputs.full_version }}/x64/lib/python${{ steps.python_version.outputs.major_version }}/site-packages/alfetcher/cache
    - name: Delete Previous Cache
      continue-on-error: true
      run: |
        gh extension install actions/gh-actions-cache
        gh actions-cache delete "${{ env.cache-key }}" --confirm
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Save Cache
      uses: actions/cache/save@v3
      with:
        path: /opt/hostedtoolcache/Python/${{ steps.python_version.outputs.full_version }}/x64/lib/python${{ steps.python_version.outputs.major_version }}/site-packages/alfetcher/cache
        key: ${{ env.cache-key }}