name: Update cached dependencies
on:
  repository_dispatch:
    types: [new_release]
  workflow_dispatch:

permissions:
  contents: read
  actions: write # require to delete cache

jobs:

  conv-cache:
    name: Update cached dependencies
    runs-on: ubuntu-latest
    env:
      cache-key: python_cache
    steps:
    - name: Wait 15 sec
      shell: bash
      run: sleep 15
    - name: Checkout current code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install anilist-helper
    - name: Delete Previous Cache
      continue-on-error: true
      run: |
        gh extension install actions/gh-actions-cache
        gh actions-cache delete "${{ env.cache-key }}" --confirm
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Save Cache
      uses: actions/cache/save@v3
      with:
        path: /opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages
        key: ${{ env.cache-key }}